### PR TITLE
Simpler. :)

### PR DESCRIPTION
**Pull request by AlvarMarkhester**

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
It's a very nice solution, but it will perform worse on average as creating the `Set` means you have to iterate through the whole of `nums` regardless of if you find duplicates or not.

**Comment by AlvarMarkhester** [comment]
> It's a very nice solution, but it will perform worse on average as creating the `Set` means you have to iterate through the whole of `nums` regardless of if you find duplicates or not. Both solutions are technically `O(N)` though.

Thanks for the feedback :)

**Review by mitchellirvin — CHANGES_REQUESTED** [review]
hi @AlvarMarkhester ! thanks for contributing!

I don't think we should remove the existing solution, as it is likely more intuitive for a new programmer (even though it is more verbose). simpler is not always easier to understand!

you're welcome to add your solution beneath the existing solution, though! it is very elegant

**Comment by Ahmad-A0** [comment]
I'll close this as stale due to the conflicts, but if you choose to resolve them and edit your solution to meet the new guidelines I'll merge this in.

**Pull request closed without merging**
