### PR TITLE
Update 0046-permutations.kt

### PR DESCRIPTION
**Pull request by FilipeLipan**
Made a solution closer to the python solution, the previous kotlin solution it's faster, but very different from the video explanation https://www.youtube.com/watch?v=s7AvT7cGdSo
 
 * **File(s) Modified**: 0046-permutations.kt
 * **Language(s) Used**: kotlin
 * **Submission URL**: https://leetcode.com/problems/permutations/submissions/942342203/

### CODE REVIEW

**Comment by a93a** [comment]
Hi! Your contribution link seems to be incorrect. Could you provide the correct one, please ?

**Comment by a93a** [comment]
@FilipeLipan Thanks! I don't see a reason to completly overrid the old solution, but we can add yours too (several different solutions in the same file are OK, as long as they differ but still manage to solve the problem).

Could you do some changes to your file and add some separation between the solutions, and I could merge.

for example:

```
// solution one
class Solution {
    fun permute(nums: IntArray): List<List<Int>> {
        //....
    }
}

// solution two 
class Solution {
    fun permute(nums: IntArray): List<List<Int>> {
        //....
    }
}
```

**Comment by FilipeLipan** [comment]
@a93a, I've done it! I'm submitting this solution because I found it annoying to study with the other solution that had a different strategy from the one in the video (https://www.youtube.com/watch?v=s7AvT7cGdSo). Please let me know if you have any questions or change requests.

**Comment by a93a** [comment]
Yes I understand, thanks for the help. You can put the video solution at top instead if you would like, I think it's better? So it's the first you see when you check the file.

**Comment by FilipeLipan** [comment]
@a93a done!!

**Comment by a93a** [comment]
Thanks a lot @FilipeLipan and thanks for your contribution!

**Pull request merged**
