### PR TITLE
Add C solutions to 104-max-depth-of-binary-tree, 110-check-for-balanced-binary-tree, 226-invert-binary-tree & 543-diameter-of-binary-tree.

### PR DESCRIPTION
**Pull request by ThBlitz**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _104-max-depth-of-binary-tree.c, 110-check-for-balanced-binary-tree.c, 226-invert-binary-tree.c, 543-diameter-of-binary-tree.c_
- **Language(s) Used**: _C_
- **Submission URL**: _https://leetcode.com/submissions/detail/779191189/, https://leetcode.com/submissions/detail/779182742/, https://leetcode.com/submissions/detail/779192677/, https://leetcode.com/submissions/detail/779194274/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
Thanks, @ThBlitz and welcome to contributing on GitHub. The PR template is the default text that pops up when you create a PR this lets you change certain fields rather than rewriting the whole text, I've edited your comment to show you what that normally looks like.

**Comment by Ahmad-A0** [comment]
It's worth noting that for this repo you don't need to include your own implementation of the `Tree` or `Sort` code leetcode provides and can add your solution exactly the way you wrote it on leetcode.

**Comment by Ahmad-A0** [comment]
Thanks again for contributing!

**Comment by ThBlitz** [comment]
Thank You ! @Ahmad-A0

**Pull request merged**
