### PR TITLE
Create: 0147-insertion-sort-list.java

### PR DESCRIPTION
**Pull request by a1exanddrovich**
- File(s) Modified: java/0147-insertion-sort-list.java 
- Language(s) Used: Java
- Submission URL: https://leetcode.com/problems/insertion-sort-list/submissions/1145408158

### CODE REVIEW

**Comment by a1exanddrovich** [comment]
Hey, @MHamiid
Could you please take a look at this?

**Comment by MHamiid** [comment]
@a1exanddrovich Please, fix the file name.

**Comment by a1exanddrovich** [comment]
@MHamiid, done.

**Review by MHamiid — APPROVED** [review]
Thanks.

**Pull request merged**
