### PR TITLE
Merge pull request #1 from neetcode-gh/main

### PR DESCRIPTION
**Pull request by aadil42**
Merging changes

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1-Two-Sum.py, 2-Add-Two-Numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/submissions/detail/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by aadil42** [comment]
Contributing solutions in JS.

**Review by aakhtar3 — COMMENTED** [review]
Few suggestions for your PR:
- Remove leading zero from file names
- The file names should follow the same casing convention as the leet code link
- Be consistent with your empty space and new lines
- Avoid do while loops
- Avoid functional programming
- Avoid Prototype and use Class
- Provide Time and Space complexity
- Provide link to problem

**Review by voski — CHANGES_REQUESTED** [review]
Aren't these all existing solutions?

According to the readme of this repository the only missing JavaScript solution is for [1851 - Minimum Interval to Include Each Query](https://leetcode.com/problems/minimum-interval-to-include-each-query/)

Also, you must update your PR description. You just left the default template.

**Comment by aadil42** [comment]
@aakhtar3 I'll review my code again. 
About the leading zero, it says in contributing guidelines that we should put the appropriate number of zeros for proper sorting.
Instead of removing zeros from my file name can I add the appropriate number of zeros to all other files? How does that sound?

**Comment by aadil42** [comment]
@voski I don't think so. https://neetcode.io/practice if you see it under NeetCode All tab. You'll find many solutions missing. It was from. And what do you mean by updating my PR description?

**Comment by voski** [comment]
> @voski I don't think so. https://neetcode.io/practice if you see it under NeetCode All tab. You'll find many solutions missing. It was from. And what do you mean by updating my PR description?

Your PR says

`Merging changes

File(s) Modified: 1-Two-Sum.py, 2-Add-Two-Numbers.py, etc...
Language(s) Used: python, javascript, etc...
Submission URL: https://leetcode.com/submissions/detail/xxxxxxxxx/`

That is a default template. You must update it to reflect your changes. For example what language are you using and what files. It also expects your leetcode submission link

Check any other PR for an example

Not sure if this repo supposed to host solutions for all the problems or just the 150.

**Comment by aadil42** [comment]
@voski Thanks mate! I'll remove this PR and I'll make one PR request per file as I go along. And I'll add each problem link in the file as well. Thanks for clarifying. I'll make one pull request and wait for your approval then I'll go ahead and do the same for other solutions. Does that sound ok?

**Comment by voski** [comment]
Sounds good.You don’t have to wait for my approval just make the PR per file as you go. Also, my comment was not about having the link in the file. It was about completing the PR template to reflect your PR. This PR had the default template without being filled in. On Oct 19, 2022, at 4:42 AM, Aadil ***@***.***> wrote:﻿
@voski Thanks mate! I'll remove this PR and I'll make one PR request per file as I go along. And I'll add each problem link in the file as well. Thanks for clarifying. I'll make one pull request and wait for your approval then I'll go ahead and do the same for other solutions. Does that sound ok?

**Comment by aadil42** [comment]
@voski  @aakhtar3  I am closing this PR. I'll make one PR per file from now on.

**Pull request closed without merging**
