### PR TITLE
11. Container with Most Water Go

### PR DESCRIPTION
**Pull request by MaratKhakim**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _11-Container-with-Most-Water.go_
- **Language(s) Used**: _go_
- **Submission URL**: _https://leetcode.com/submissions/detail/757508764/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
Thanks, @MaratKhakim!

**Comment by MaratKhakim** [comment]
Thanks @Ahmad-A0 for merging it. Would you mind telling me how I can get Collaborator permission?

**Comment by Ahmad-A0** [comment]
I believe you can just tag -@-neetcode-gh and ask. That's what worked for me 👍

**Comment by MaratKhakim** [comment]
Thanks @Ahmad-A0. @neetcode-gh please, grant me Collaborator permission so that I can merge PRs

**Pull request merged**
