### PR TITLE
Create: 1721-swapping-nodes-in-a-linked-list.go

### PR DESCRIPTION
**Pull request by StormbornYB**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1721-swapping-nodes-in-a-linked-list.go_
- **Language(s) Used**: _Go_
- **Submission URL**: _https://leetcode.com/problems/swapping-nodes-in-a-linked-list/submissions/1019113592/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### CODE REVIEW

**Comment by StormbornYB** [comment]
@felivalencia3 @chetannada @mdmzfzl @sujal-goswami 
 Hey guys! I'd appreciate, if you take a look :)
 I am looking forward to merge more of Neetcode solutions in Go.

**Review by felivalencia3 — APPROVED** [review]

**Comment by felivalencia3** [comment]
Looks good, thanks for reaching out!

**Comment by mdmzfzl** [comment]
Make sure your approach is not too different from the one's explained in NeetCode videos as some people complain about solutions that are completely different. All the best solving more problems!

**Comment by chetannada** [comment]
> @felivalencia3 @chetannada @mdmzfzl @sujal-goswami Hey guys! I'd appreciate, if you take a look :) I am looking forward to merge more of Neetcode solutions in Go.

Great. Keep posting good solution.

**Pull request merged**
