### PR TITLE
add solution for leetcode problem 1466 in Kotlin

### PR DESCRIPTION
**Pull request by t3chkid**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1466-reorder-routes-to-make-all-paths-lead-to-the-city-zero.kt_
- **Language(s) Used**: _Kotlin_
- **Submission URL**: _https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/submissions/915441568/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by t3chkid** [comment]
@a93a

**Comment by t3chkid** [comment]
@a93a As you mentioned in the previous pr, I tried to assign the pr to you. But, I guess I don't have the permission to assign pr's to assignees.

**Comment by t3chkid** [comment]
Please someone have a look at this pr, it's been a while since I opened it.

**Comment by a93a** [comment]
Apologies, I have not been very active. Thanks for your contribution, looks good!

**Pull request merged**
