### PR TITLE
Create: 0650-can-place-flowers.cpp

### PR DESCRIPTION
**Pull request by WildChildx**
Code for leetcode problem 14-Longest-Common-Prefix in cpp.

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1-Two-Sum.py, 2-Add-Two-Numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/submissions/detail/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by tahsintunan** [comment]
Please provide/update the necessary information (Files Modified, Language, Submission URL) in your PR.

**Comment by WildChildx** [comment]
> Please provide/update the necessary information (Files Modified, Language, Submission URL) in your PR.

- File(s) Modified: 14-Longest-Common-Prefix
- Language(s) Used: cpp
- Submission URL: https://leetcode.com/problems/longest-common-prefix/submissions/862128717/

**Review by tahsintunan — CHANGES_REQUESTED** [review]
1. Rename the files according to the guideline [here](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md#contributing-guidelines) (e.g. only small case letters, 4 digits in problem number, etc)
2. Move the Java solution inside `java` directory.
3. Add appropriate extensions to the file names (i.e. `0014-longest-common-prefix.cpp`, `.....java`)

**Comment by WildChildx** [comment]
File(s) Modified: cpp/0014-Longest-Common-Prefix ,cpp/0605-Can-Place-Flowers
Language(s) Used: cpp
Submission URL: https://leetcode.com/problems/longest-common-prefix/submissions/862128717/ , 
                            https://leetcode.com/problems/can-place-flowers/submissions/863588986/

**Comment by WildChildx** [comment]
File(s) Modified: cpp/0014-longest-common-crefix.cpp , cpp/0605-can-place-flowers.cpp
Language(s) Used: cpp
Submission URL: https://leetcode.com/problems/longest-common-prefix/submissions/862128717/ ,
https://leetcode.com/problems/can-place-flowers/submissions/863588986/

**Comment by WildChildx** [comment]
File(s) Modified:  cpp/0605-can-place-flowers.cpp
Language(s) Used: cpp
Submission URL:  https://leetcode.com/problems/can-place-flowers/submissions/863588986/

**Comment by a93a** [comment]
The submission url is still missing for [cpp/14-Longest-Common-Prefix](https://github.com/neetcode-gh/leetcode/pull/1561/files#diff-6febde5389482b3e9c3b77d54efc44c23ce84249c2b1cffa539df0313c5a6b28) and the filename is in the wrong format. 

Could you please resolve this? 

Thanks

**Comment by WildChildx** [comment]
Solution already exists in the repo for cpp

**Pull request closed without merging**
