### PR TITLE
Adds solutions for problems 17 & 51 in Kotlin

### PR DESCRIPTION
**Pull request by t3chkid**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _17-Letter-Combinations-of-a-Phone-Number.kt, 51-N-Queens.kt_
- **Language(s) Used**: _Kotlin._
- **Submission URL**: _https://leetcode.com/problems/letter-combinations-of-a-phone-number/submissions/862446043/, https://leetcode.com/problems/n-queens/submissions/860468704/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### CODE REVIEW

**Comment by t3chkid** [comment]
It's been more than a month since I first created this pr. I request someone to have a look at it.

**Comment by a93a** [comment]
Hi! 

There are some conflicts. 51 n-queens already exists in the repo, but you can still contribute for problem 17. Also, there is some conflicting issues with the Readme file.

Could you also rename your file to follow the repo naming conventions? For filenames, it's `<language>/<problem-number>-name-of-problem.<language-extension>` (e.g. `java/0001-two-sum.java`)

Thanks!

**Comment by t3chkid** [comment]
I've resolved the conflicts in the readme file and removed the solution for N-Queens.

**Comment by a93a** [comment]
Thank you very much for your contribution. I changed the filename for you. But in the future please use the naming convention. And apologies that it took so long to review your PR. Thank you.

**Comment by a93a** [comment]
If you are doing more Kotlin submissions in the future, please assign me to it and I will take a look ASAP :)

**Comment by t3chkid** [comment]
> Thank you very much for your contribution. I changed the filename for you. But in the future please use the naming convention. And apologies that it took so long to review your PR. Thank you.

Thank you. Apologies for not using the correct format. I've been contributing to this repo for quite some time, and I don't remember using leading 0's in the file name and also using all lowercase letters. I've just noticed that the repo follows this convention now. I'll make sure that I follow this naming convention in the future 👍🏻

**Comment by a93a** [comment]
No need to apologise!  You are correct, I think neetcode changed it a month ago or so (after you've made this PR!)

**Pull request merged**
