### PR TITLE
Create: 5782-maximum-alternating-subsequence-sum.cpp

### PR DESCRIPTION
**Pull request by ashutosh2706**
- **File(s) Modified**: cpp/5782-maximum-alternating-subsequence-sum.cpp
- **Language(s) Used**: C++
- **Submission URL**: https://leetcode.com/problems/maximum-alternating-subsequence-sum/submissions/903085520/

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### CODE REVIEW

**Comment by a93a** [comment]
Hi, could you correct the file name please? The problem number is 1911 and not 5782?

**Comment by a93a** [comment]
Did you accidently close this?

**Comment by ashutosh2706** [comment]
I've created a new PR with a new branch just now. You can merge that one

**Comment by a93a** [comment]
Okay, thanks!

**Pull request closed without merging**
