### PR TITLE
Creating a JS file for solving-pascals tringle.

### PR DESCRIPTION
**Pull request by aadil42**
- File(s) Created: 118-pascals-triangle.js
- Language(s) Used: JavaScript
- Submission URL: https://leetcode.com/submissions/detail/828733368/

### CODE REVIEW

**Comment by aadil42** [comment]
Hey, @voski Please tell me if I did it right this time.

**Comment by aadil42** [comment]
Hey @voski, Did I do it wrong again? please let me know. Thank you

**Comment by aadil42** [comment]
Hey @voski, my PR hasn't been merged yet so this is just a kind reminder. Let me know if I need to do anything.

**Comment by diss1993** [comment]
I think you can do it without checking if size > 2

Just don't write on JS. I can share my solution on Swift.
It would be less code and more understandable.

`class Solution {
 func generate(_ numRows: Int) -> [[Int]] {
    var result = [[Int]](repeating: [1], count: numRows)
    for i in 1..<numRows {
        result[i] = [Int](repeating: 1, count: i + 1)
        for j in 1 ..< i {
            result[i][j] = result[i-1][j-1] + result[i-1][j] 
        } 
    }
    return result
 }
}`

**Comment by aadil42** [comment]
@diss1993 I'll look into your solution soon. Thanks for sharing.

**Comment by aadil42** [comment]
@voski I thought you had merge permission. Anyway, thank you for your support and advice on how to make a proper PR. Thanks, huge thank you!

**Comment by aadil42** [comment]
@voski btw, I know you don't have merge permission. But is my PR ok? I just wanted to ask to make sure. Thank you again!

**Comment by aadil42** [comment]
@voski Thank you, brother! I fixed the formatting. I didn't what text to make italics so left it. but I did the bullet points.

**Comment by Ahmad-A0** [comment]
Thanks for contributing (and collaborating)!

**Pull request merged**
