### PR TITLE
Create 0392_is_subsequence.java

### PR DESCRIPTION
**Pull request by tharunkanna14**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _4-Is-Subsequence_
- **Language(s) Used**: _java_
- **Submission URL**: _https://leetcode.com/submissions/detail/819227305/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Review by Ahmad-A0 — CHANGES_REQUESTED** [review]
I don't think a separate nested directory is needed for the neetcode_all problems, they can be added in the same folder as the current java solutions.

**Comment by tharunkanna14** [comment]
> I don't think a separate nested directory is needed for the neetcode_all problems, they can be added in the same folder as the current java solutions.

I have moved my code to the same folder that has java solutions like you said.

**Review by tharunkanna14 — COMMENTED** [review]
I have moved the code to the directory which has all java solutions.

**Comment by Ahmad-A0** [comment]
Thanks, @tharunkanna14!

**Pull request merged**
