### PR TITLE
Create 1822-sign-of-the-product-of-an-array.java

### PR DESCRIPTION
**Pull request by leahjia**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1822-sign-of-the-product-of-an-array.java_
- **Language(s) Used**: _Java_
- **Submission URL**: _https://leetcode.com/problems/sign-of-the-product-of-an-array/submissions/976638518/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by sujal-goswami** [comment]
This question is not on NeetCode Website. Please submit PRs only for available questions on the website.

**Comment by leahjia** [comment]
This question is on the Needcode website named _Sign of An Array_, which is named differently on leetcode (_Sign of the Product of an Array_) and is shown in the video. Also, by searching the question number 1822 on this repo you can also find the question listed in the readme table.

**Comment by leahjia** [comment]
> This question is not on NeetCode Website. Please submit PRs only for available questions on the website.

@sujal-goswami Please reopen as this is a valid request, or I can submit a new PR. Thanks.

**Review by sujal-goswami — APPROVED** [review]

**Comment by sujal-goswami** [comment]
Next time please make sure to Name the file same as Listed in the Readme Table. Otherwise it is difficult for GitHub Action to work properly.

**Pull request merged**
