### PR TITLE
Create 2390 - Removing Stars From a String.py

### PR DESCRIPTION
**Pull request by yryryy**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _0001-two-sum.py, 0002-add-two-numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by felivalencia3** [comment]
Hello, can you edit your pull request template to include your leetcode submission URL as well as File(s) modified and Language(s) used? Then I can merge your PR.

**Comment by felivalencia3** [comment]
Forget that, I saw that you included the link in the code. Merging now.

**Comment by felivalencia3** [comment]
yryryy, after I merged your pull request I noticed that you had written your code inside a folder called "python " with a space at the end. This created a new folder and led to a new column in our ReadMe being automatically created. I have fixed this and moved your file into the main python folder. But for the future, make sure you are writing your files in the correct folder.

**Comment by yryryy** [comment]
Apologies for that, I'm fairly new to Github and still trying to figure out how things work in here

**Pull request merged**
