### PR TITLE
Create: 0538-convert-bst-to-greater-tree.java

### PR DESCRIPTION
**Pull request by a1exanddrovich**
- File(s) Modified: 0538-convert-bst-to-greater-tree.java
- Language(s) Used: Java
- Submission URLs: 
 https://leetcode.com/problems/convert-bst-to-greater-tree/submissions/1161453515 - recursive solution
 https://leetcode.com/problems/convert-bst-to-greater-tree/submissions/1161444952 - iterative solution

### CODE REVIEW

**Comment by a1exanddrovich** [comment]
Hey, @MHamiid
Could you please take a look at this?

**Comment by MHamiid** [comment]
Hello @a1exanddrovich, please, separate the two solutions.

**Comment by a1exanddrovich** [comment]
@MHamiid, unsure I got you right, you mean to place them in different files, don't you? I haven't seen this in other PRs.
I decided to separate the solutions as it's done in this [PR](https://github.com/neetcode-gh/leetcode/pull/1667/files).
Please let me know if this is correct.

**Comment by a93a** [comment]
@a1exanddrovich He meant to separate the solutions so each solution "is a separate class" with some comments about the way it is solved.

Something like this:

```
// recursive solution
public Solution {
    function getSomeValues() {
        ... 
     }
}

// iterate solution
public Solution {
    function getSomeValues() {
        ...
     }
}
```

**Comment by a1exanddrovich** [comment]
Hey @a93a, thanks for the heads up!
I've updated the code.

**Comment by a93a** [comment]
Thank you! I have merged this now, thank you for your contribution.

**Pull request merged**
