### PR TITLE
Create: 0080-remove-duplicates-from-sorted-array-II.java

### PR DESCRIPTION
**Pull request by viet2307**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _java/0080-remove-duplicates-from-sorted-array-II.java_
- **Language(s) Used**: _Java_
- **Submission URL**: _https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/submissions/976346345/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Review by sujal-goswami — CHANGES_REQUESTED** [review]
Please Read Contributing.md carefully. your PR name does not follow the contributing guidelines.

**Review by chetannada — COMMENTED** [review]
make your commit name start with `Create` and your `Leetcode Question name` and end with `.java` for ex: `Create 0080-remove-duplicates-from-sorted-array-II.java`

**Comment by viet2307** [comment]
Hi guys, so sorry for the very late reply. Somehow git did not sent me any notifications about this and it totally slipped my mind.
Anyway, I changed the PR name according to the guidelines. Please give it a look if you have the time.
Thank you very much!

**Comment by Ykhan799** [comment]
This solution is identical to the current Java solution in the repo, will close out this PR.

**Pull request closed without merging**
