### PR TITLE
Added leetcode solutions

### PR DESCRIPTION
**Pull request by diva-21**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _0041 - First Missing Positive, 0290 - Word Pattern,1930 - Unique Length 3 Palindromic Subsequences
- **Language(s) Used**: cpp
- **Submission URL**: _ https://leetcode.com/problems/word-pattern/submissions/868580925/ ,  https://leetcode.com/problems/unique-length-3-palindromic-subsequences/submissions/868581664/ , https://leetcode.com/problems/first-missing-positive/submissions/868581995/

### CODE REVIEW

**Review by tahsintunan — CHANGES_REQUESTED** [review]
Please rename the files as per the instructions given [here](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md#contributing-guidelines)

**Comment by diva-21** [comment]
> Please rename the files as per the instructions given [here](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md#contributing-guidelines)

I have made the changes as per instructed @tahsintunan

**Comment by tahsintunan** [comment]
> > Please rename the files as per the instructions given [here](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md#contributing-guidelines)
> 
> I have made the changes as per instructed @tahsintunan

Make sure the `problem-number` is formatted as four digits adding leading zeroes if necessary (e.g. `0041` instead of `41`, `0290` instead of `290`)

**Comment by diva-21** [comment]
> > > Please rename the files as per the instructions given [here](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md#contributing-guidelines)
> > 
> > 
> > I have made the changes as per instructed @tahsintunan
> 
> Make sure the `problem-number` is formatted as four digits adding leading zeroes if necessary (e.g. `0041` instead of `41`, `0290` instead of `290`)

changes did,sorry for silly mistakes @tahsintunan

**Review by tahsintunan — APPROVED** [review]

**Comment by tahsintunan** [comment]
Thank you.

**Pull request merged**
