### PR TITLE
Replace recursive implementation with iterative implantation for 235. Lowest Common Ancestor of a Binary Search Tree in Kotlin

### PR DESCRIPTION
**Pull request by t3chkid**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _235-Lowest-Common-Ancestor-Of-Binary-Search-Tree.kt_
- **Language(s) Used**: _Kotlin_
- **Submission URL**: _https://leetcode.com/submissions/detail/788472537/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
Could we keep both solutions under different names eg. `lowestCommonAncestorIterative`/`lowestCommonAncestorRecursive`?

**Comment by t3chkid** [comment]
> Could we keep both solutions under different names eg. `lowestCommonAncestorIterative`/`lowestCommonAncestorRecursive`?

No, because the iterative solution has a space complexity of O(1),  which is objectively better than the space complexity of the recursive solution, which is O(n).

**Comment by Ahmad-A0** [comment]
My bad, I didn't spot the difference in space complexity. Thanks, @t3chkid!

**Comment by t3chkid** [comment]
> My bad, I didn't spot the difference in space complexity. Thanks, @t3chkid!

No worries ✌️

**Pull request merged**
