### PR TITLE
create 1091-shortestpath-in-binary-matrix.cpp

### PR DESCRIPTION
**Pull request by adityaiiitr**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1091-shortest-path-in-binary-matrix.cpp_
- **Language(s) Used**: _cpp_
- **Submission URL**: _https://leetcode.com/problems/shortest-path-in-binary-matrix/submissions/1160811958/_

Note: I have used the same logic as it was described in the youtube video. Thanks!

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by adityaiiitr** [comment]
Leetcode Question [787. Cheapest Flights Within K Stops](https://leetcode.com/problems/cheapest-flights-within-k-stops/)

Previous Solution Provided: [Github Solution](https://github.com/neetcode-gh/leetcode/blob/main/cpp/0787-cheapest-flights-within-k-stops.cpp)

New Solution Added : [Submission Link](https://leetcode.com/problems/cheapest-flights-within-k-stops/submissions/1161273229/)

Neetcode video: [YT Link ](https://www.youtube.com/watch?v=5eIK3zUdYmE)

**Comment by a93a** [comment]
Your solution for both looks great! 

However, I want to suggest a small edit for `787. Cheapest Flights Within K Stops` problem. 

There is already a solution using Dijkstras, and it is also a valid way to solve it so we do not need to delete it.  It is always good to keep other ways of solving a problem, but the first solution in the file should always be the one following the video. And use of commenting to avoid any confusion,

I would suggest that you edit the file to add yours while keeping the other solution. You can put yours first (Since it is the one following the video solution) and put the other solution below. They should be separated in two `Solution` classes, should look something like this:

```
// Your solution here, bellman-ford....
class Solution {
    int findCheapestPrice() {
        // ...
    }
}

// Other solution here, dijkstras....
class Solution {
    int findCheapestPrice() {
        // ...
    }
}
```

**Comment by adityaiiitr** [comment]
Thanks @a93a for the review I had done the necessary code  changes.

**Comment by a93a** [comment]
Thank you @adityaiiitr ! I have merged this now.

**Comment by a93a** [comment]
@adityaiiitr Please feel free to create seperate PR for each Leetcode problem in the future, this makes it easier to read & review :smiley:

**Pull request merged**
