### PR TITLE
Create 344-Reverse-String.py and Create 680-Valid-Palindrome-II.py

### PR DESCRIPTION
**Pull request by NN-Liu**
File(s) Modified: 344-Reverse-String.py
Language(s) Used: Python
Submission URL: https://leetcode.com/submissions/detail/844613172/

### CODE REVIEW

**Comment by NN-Liu** [comment]
I created the solution for 344-Reverse-String in Python code

**Comment by NN-Liu** [comment]
I created solution for Python/680-Valid Palindrome II.py

**Comment by aadil42** [comment]
Bro, you need to provide the file name, the language used, and the link to your submission. check your very first comment. 

There it says:
File(s) Modified: 1-Two-Sum.py, 2-Add-Two-Numbers.py, etc...
Language(s) Used: python, javascript, etc...
Submission URL: https://leetcode.com/submissions/detail/xxxxxxxxx/

just add the file name, used language, and submission link in these three lines.
check out this PR for reference https://github.com/neetcode-gh/leetcode/pull/1459

**Comment by Ahmad-A0** [comment]
Thanks, @NN-Liu and @aadil42!

**Pull request merged**
