### PR TITLE
Added 0706-design-hashmap.cs

### PR DESCRIPTION
**Pull request by DaltonVislisel**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**:0706-design-hashmap.cs_
- **Language(s) Used**: _csharp_
- **Submission URL**: _https://leetcode.com/submissions/detail/1116845362/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Review by sujal-goswami — APPROVED** [review]
Hey @DaltonVislisel , Can you please delete the readme file changes? It will update automatically after a successful PR merge.

**Comment by DaltonVislisel** [comment]
> Hey @DaltonVislisel , Can you please delete the readme file changes? It will update automatically after a successful PR merge.

Done. Looks like that readme change happened automatically when I created my PR?

**Comment by DaltonVislisel** [comment]
@sujal-goswami, it looks like it automatically updated again. Do I need to abandon this PR and try again or can we let it go through?

**Comment by sujal-goswami** [comment]
Now it looks fine Thanks for your contribution.

**Pull request merged**
