### PR TITLE
Added 212-Word-Search-II.java

### PR DESCRIPTION
**Pull request by Raven1233**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _212-Word-Search-II.java_
- **Language(s) Used**: _java_
- **Submission URL**: _https://leetcode.com/submissions/detail/760405519/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by sergeimellow** [comment]
It's funny we worked on the same thing at the same time except mine is just a port of the existing python solution.
image
I'll be happy with whoever's merges, just did this for fun and in case it helps anyone out studying this problem.

**Comment by Raven1233** [comment]
> It's funny we worked on the same thing at the same time except mine is just a port of the existing python solution. image I'll be happy with whoever's merges, just did this for fun and in case it helps anyone out studying this problem.

Haha that's true but yeah your solution definitely is faster than mine. Would love if you could explain your solution to me. My solution is simply a modification on Neetcode's provided java solution for Word-Search-I, using the concept of his Word-Search-II python solution, as is on his YT channel.

**Comment by Ahmad-A0** [comment]
😬 I merged his first going from top down on PR page, however we welcome multiple solutions, so feel free to pull upstream changes and add your solution as well.

**Comment by Raven1233** [comment]
It's alright I will continue to help with the other missing solutions.

**Comment by Raven1233** [comment]
> 😬 I merged his first going from top down on the PR page, however we welcome multiple solutions, so feel free to pull upstream changes and add your solution as well.

It's alright I will continue to help with the other missing solutions for the Java repository.

**Pull request closed without merging**
