### PR TITLE
Sri Hari: Neetcode-150/added-5-articles

### PR DESCRIPTION
**Pull request by Srihari2222**
### Created articles

- Took roughly (5 hours 30 min) for this work.
-  There are more than 2 solutions in each article.
- - Please review this Navi.

### CODE REVIEW

**Comment by neetcode-gh** [comment]
Also, in the future you can directly assign me as the reviewer in github.

**Comment by Srihari2222** [comment]
Thanks for the feedback, you can mention more if needed as I am making the changes you mentioned.

**Comment by Srihari2222** [comment]
I added the changes you mentioned and also I didn't add description in top-k article thougt the time complexity is nlogk because k is directly mentioned in code. Whats your opinion on this?

**Comment by neetcode-gh** [comment]
@Srihari2222 Thanks, looks good! I think it might be better to also add it for top-k, since then we can explicitly mention that n is the length of the input. It's minor though, I will merge this pull request as-is. If you wanna make more changes feel free to add them in a separate PR.

I will be reviewing your future contributions less carefully, so i'll trust your judgement on those. Thanks again!

**Comment by neetcode-gh** [comment]
@Srihari2222 Also, in the future could you tag me @neetcode-gh in your comments. I currently have github notifications off by default so this will help me respond more quickly.

**Pull request merged**
