### PR TITLE
C Solution to Neetcode: 148 SortList

### PR DESCRIPTION
**Pull request by javiermon**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _c/148-Sort-List.c_
- **Language(s) Used**: _c_
- **Submission URL**: _https://leetcode.com/problems/sort-list/submissions/880346565/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### CODE REVIEW

**Comment by a93a** [comment]
Hi! 

Would you be kind to provide your Leetcode submission URL for your solution?

And could you please also rename your file to follow the repo naming conventions? For filenames, it's `<language>/<problem-number>-name-of-problem.<language-extension>` (e.g. `java/0001-two-sum.java`)

**Comment by javiermon** [comment]
Thanks for the review, it's updated now.

**Comment by a93a** [comment]
Thanks! I changed the filename for you, but please keep in mind for future PR's. Thanks for yuor contribution!

**Comment by javiermon** [comment]
Sorry I missed the leading 0 (at the time I created the PR it was only 3 digits...)

**Comment by a93a** [comment]
No worries at all! Yes, you are correct, I think the filenaming style changed sometimes after that. Also, apologies that your PR wasn't reviewed earlier!

**Pull request merged**
