### PR TITLE
A Runtime 62 ms, Memory 14 MB solution

### PR DESCRIPTION
**Pull request by pomelo**
Beats 95.9% and  92.93% respectively

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1-python/3-Longest-Substring-Without-Repeating-Characters.py_
- **Language(s) Used**: _python_
- **Submission URL**: _https://leetcode.com/problems/longest-substring-without-repeating-characters/submissions/812391532/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
Sorry, I can't merge a new solution with no difference in complexity. Please see the contributing guidelines.

**Comment by nikhila01** [comment]
Not sure why this solution got merged despite the comment that it didn't meet the guidelines and wouldn't be merged.

NeetCode had a perfectly fine solution. This only changed the variable names (most of which are just single letters now) and changed a for loop to a while loop.

**Comment by Ahmad-A0** [comment]
Sorry about that, my mistake.

**Comment by nikhila01** [comment]
No problem, thanks for reverting!

**Pull request merged**
