### PR TITLE
added 1_twoSum solution golang

### PR DESCRIPTION
**Pull request by zuruoke**

### CODE REVIEW

**Comment by mitchellirvin** [comment]
hi @zuruoke ! thanks for contributing, and sorry for the delay in reviewing. do you mind updating your directory naming convention to be `snake_case` to match existing folders?, e.g. `go/blind_75/arrays_&_hashing/1-Two-Sum.go`

**Review by mitchellirvin — CHANGES_REQUESTED** [review]
hi @zuruoke ! thanks for contributing, and sorry for the delay in reviewing. do you mind updating your directory naming convention to be `snake_case` to match existing folders?, e.g. `go/blind_75/arrays_&_hashing/1-Two-Sum.go`

**Comment by zuruoke** [comment]
okay @mitchellirvin

**Comment by iamtodor** [comment]
@mitchellirvin perhaps it would be better to use the power of GitHub actions for folders and files naming convention? and same for the code style

**Pull request merged**
