### PR TITLE
Create minimum_size_subarray_sum.cpp

### PR DESCRIPTION
**Pull request by Vitali-Matteo**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _minimum_size_subarray_sum.cpp_
- **Language(s) Used**: _C++_
- **Submission URL**: _https://leetcode.com/submissions/detail/780162348/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
Sorry, I have to put this PR on hold for the time being due to the way the C++ directory is set out. I'll leave this open and make the changes required to merge it once I've sorted out the other files.

**Comment by Vitali-Matteo** [comment]
Hi! Thank for your reply. 

Did I do something wrong branching and pulling the request? It's the first time for me using GitHub.

**Comment by Ahmad-A0** [comment]
No you did everything right, the C++ directory is just set out differently to the others. Once it's sorted I'll get this merged ASAP. Thanks for contributing!

**Comment by Vitali-Matteo** [comment]
I've edited my CPP file as you requested. Thank you.

**Comment by Ahmad-A0** [comment]
Thanks, @Vitali-Matteo!

**Pull request merged**
