### PR TITLE
Create: 605-Can-Place-Flowers.java

### PR DESCRIPTION
**Pull request by DecodeAndCode**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1-Two-Sum.py, 2-Add-Two-Numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### CODE REVIEW

**Review by aakhtar3 — CHANGES_REQUESTED** [review]
You should git ignore your ide files

**Comment by DecodeAndCode** [comment]
@aakhtar3 

> You should git ignore your ide files

how should I do it then

**Comment by aakhtar3** [comment]
- Unstage your 1,556 files from your commit
- Update [.gitignore](https://github.com/neetcode-gh/leetcode/blob/main/.gitignore) to include `.idea/**`
- Stage the update on .gitignore to your commit

**Comment by DecodeAndCode** [comment]
I made the changes

**Comment by aakhtar3** [comment]
You need to update your commit to unstage all the files

**Comment by DecodeAndCode** [comment]
done

**Comment by aakhtar3** [comment]
Still seeing 1,558 files changed

**Comment by DecodeAndCode** [comment]
IDK that's happening

**Comment by DecodeAndCode** [comment]
shall I close pr and start a new one

**Pull request closed without merging**
