### PR TITLE
875. Koko Eating Bananas

### PR DESCRIPTION
**Pull request by benjiwright**
- **File(s) Modified**: _875-Koko-Eating-Bananas.cs_
- **Language(s) Used**: _csharp_
- **Submission URL**: _https://leetcode.com/submissions/detail/793338831/_

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
Sorry, this doesn't pass [all test cases](https://leetcode.com/submissions/detail/793338831/).

**Comment by benjiwright** [comment]
You the code you ran in the [failing submission](https://leetcode.com/submissions/detail/793338831/) above is different from the [code I submitted in the PR](https://github.com/neetcode-gh/leetcode/pull/1061/commits).

Mine:
```
#11 long hours = 0;
```

Yours
```
#10 var hours = 0;
```

Yours will fail because `var` will create an `int` instead of the required `long`

Please verify your code.

**Comment by benjiwright** [comment]
@Ahmad-A0 👆🏻

**Comment by Ahmad-A0** [comment]
My mistake, @benjiwright. I used the "Submission URL" you included in the PR comment rather than the code.

**Comment by Ahmad-A0** [comment]
Thanks, @benjiwright!

**Comment by benjiwright** [comment]
That was my bad!!! The link I provided for `submission url` was wrong.  I'm sorry <3

**Pull request merged**
