### PR TITLE
Sri Hari: Neetcode-150/articles

### PR DESCRIPTION
**Pull request by Srihari2222**
@neetcode-gh 

- Took 6 hours for this work.
- Please review this.

### CODE REVIEW

**Comment by neetcode-gh** [comment]
Thanks @Srihari2222 looks good, just some minor changes:

1. Can we rename the "Tortoise And Hare Algorithm" solution to "Fast and Slow Pointers"
2. For the brute force solution of remove-node-from-end-of-list, can we make the time complexity variables lower case, just for consistency. e.g. O(N) to O(n)

This is really minor, but might be worth doing.

**Comment by Srihari2222** [comment]
@neetcode-gh 
yeah, I will rename it. But for the O(n), should I write the comment as the problem has n as a parameter?

**Comment by Srihari2222** [comment]
@neetcode-gh 
I have renamed the name.
Waiting for the confirmation regarding the O(N).

**Comment by neetcode-gh** [comment]
@Srihari2222 good point, capital N is fine in that case.

**Pull request merged**
