### PR TITLE
Add solution for 295-Find-Median-from-Data-Stream using heaps

### PR DESCRIPTION
**Pull request by sambakk**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _javascript/295-Find-Median-from-Data-Stream(Using Heaps).js_
- **Language(s) Used**: _javascript_
- **Submission URL**: _https://leetcode.com/submissions/detail/773520205/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

- **Notes**:
I wrote this solution because the existing one **doesn't use heaps**.
Heaps are not supported natively in JS. That's why Leetcode uses @datastructures-js/priority-queue@**5.3.0** to code Heaps in JS

### CODE REVIEW

**Comment by Ahmad-A0** [comment]
If possible could you add this solution to the existing file renaming the previous function to `MedianFinder2`. This is needed for when neetcode.io swaps to automatically linking the solutions.

**Comment by sambakk** [comment]
Done.

**Comment by sambakk** [comment]
@Ahmad-A0 sorry I've closed the pull request by mistake

**Comment by aakhtar3** [comment]
There is a typo in the file name? Are we sticking with capital first word?
See updated file
https://github.com/neetcode-gh/leetcode/blob/main/javascript/295-Find-Median-From-Data-Stream.js

**Pull request closed without merging**
