### PR TITLE
refactor: js - binary search

### PR DESCRIPTION
**Pull request by aakhtar3**

### CODE REVIEW

**Comment by mitchellirvin** [comment]
thanks @aakhtar3 !

**Comment by mitchellirvin** [comment]
@aakhtar3 if you have any interest in becoming a collaborator on this repo let us know! your PR quality is great, and we'd always appreciate more folks to help review PRs and keep the repo squeaky clean :)

**Comment by aakhtar3** [comment]
@mitchellirvin Yes, I am interested in becoming a collaborator!

**Comment by mitchellirvin** [comment]
awesome. @neetcode-gh has the `owner` role on the repo, thoughts on adding @aakhtar3 as a collaborator? he's made several high quality contributions and has been a pleasure to interact with through all of them

**Pull request merged**
