### PR TITLE
Delete mixed case file 1143-Longest-Common-Subsequence.java

### PR DESCRIPTION
**Pull request by coopers**
- **File(s) Modified**: _1143-longest-common-subsequence.java_
- **Language(s) Used**: _java_
- **Submission URL**: _N/A_

There is a single version of each file. For some reason there are 2 versions of the file 1143-longest-common-subsequence.java in the repo. One version is lowercase and the other is mixed case, 1143-Longest-Common-Subsequence.java. The mixed case file is Untracked by git, so I removed it.

### CODE REVIEW

**Review by sujal-goswami — APPROVED** [review]
Thanks for your contribution @coopers

**Comment by coopers** [comment]
I'm happy to help @sujal-goswami 
I noticed other mixed case files in the repo.
Let me know if you want me to remove them too, defaulting to the lowercase filename.

**Comment by sujal-goswami** [comment]
Yes, please go ahead with defaulting to lowercase filenames for consistency. I really appreciate your contribution.

**Comment by coopers** [comment]
Cool!
I think this is the list of all mixed-case filenames within a code directory.
go/0236-Lowest-Common-Ancestor-of-Binary-Tree.go
go/0852-Peak-Index-In-A-Mountain-Array.go
go/0063-Unique-Paths-II.go
go/0876-Middle-Of-The-Linked-List.go
python/1137-N-th-Tribonacci-Number.py
python/0119-Pascal-Triangle-II.py
java/1275-Find-Winner-on-a-Tic-Tac-Toe-Game.java
java/2328-Number-of-Increasing-Paths-in-a-Grid.java
java/2390-Removing-Stars-From-a-String.java
java/1160-Find-Words-That-Can-Be-Formed-by-Characters.java
java/0402-Remove-K-Digits.java
java/2310-Sum-of-Numbers-With-Units-Digit-K.java
java/1155-Number-of-Dice-Rolls-With-Target-Sum.java
java/0456-132-Pattern.java
cpp/2235-Add-Two-Integers.cpp
cpp/1641-Count-Sorted-Vowel-Strings.cpp
cpp/2315-Count-Asterisks.cpp
cpp/0387-First-Unique-Character-In-A-String.cpp
cpp/0122 - Best Time to Buy And Sell Stock II.cpp
cpp/0219-Contains-Duplicate-II.cpp
cpp/0236-Power-Of-Three.cpp
cpp/1213-Maximum-Product-Difference-Between-Two-Pairs.cpp
cpp/0740-Delete-And-Earn.cpp
cpp/1512-Number-Of-Good-Pairs.cpp
cpp/0279-Perfect-Squares.cpp
cpp/0278-First-Bad-Version.cpp
cpp/1920-Build-Array-From-Permutation.cpp
cpp/0342-Power-Of-Four.cpp
csharp/1480-Running-Sum-Of-1D-Array.cs
javascript/1486-XOR-operation-in-an-array.js
javascript/1863-sum-of-all-subset-XOR-totals.js
javascript/1514-Path-With-Maximum-Probability.js

**Comment by coopers** [comment]
OK, just submitted the pull request.

**Pull request merged**
