### PR TITLE
Updating 70.climbing_stairs.cpp

### PR DESCRIPTION
**Pull request by aniruddhakj**
Updating the solution with a more easily understandable code according to the video solution

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _climbing_stairs.cpp_
- **Language(s) Used**: _C++_
- **Submission URL**: _https://leetcode.com/submissions/detail/816998657/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/submissions/detail/xxxxxxxxx/"

### CODE REVIEW

**Review by Ahmad-A0 — DISMISSED** [review]
Please add your solution to the top of the file, renaming the class of the previous one.

**Comment by aniruddhakj** [comment]
I didn't quite understand, should I keep both the solutions in the file including the previous one by just modifying the classname? 

Thanks,

**Comment by Ahmad-A0** [comment]
Yep that's correct,  e.g `SolutionIterative`, `SolutionRecursive` for a file that contains both an iterative and recursive approach.

**Review by aniruddhakj — COMMENTED** [review]
Please check the PR now, and let me know if there's anything else needed from my end

**Comment by Ahmad-A0** [comment]
That's all, @aniruddhakj. Thanks for contributing.

**Comment by Ahmad-A0** [comment]
That's all, @aniruddhakj. Thanks for contributing!

**Comment by aniruddhakj** [comment]
Anytime!

**Pull request merged**
