### PR TITLE
Create 2520-count-the-digits-that-divide-a-number.js

### PR DESCRIPTION
**Pull request by chetannada**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**:  2520-count-the-digits-that-divide-a-number.js
- **Language(s) Used**:  javascript
- **Submission URL**: https://leetcode.com/problems/count-the-digits-that-divide-a-number/submissions/1006700949/

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Review by sujal-goswami — COMMENTED** [review]
hey @chetannada,
Problem `2520` is not mentioned in the Readme file. hence we are unable to merge it; nevertheless, you may help with the other problems on the list.

For more details Read [CONTRIBUTING.md](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md)

**Comment by chetannada** [comment]
> hey @chetannada, Problem `2520` is not mentioned in the Readme file. hence we are unable to merge it; nevertheless, you may help with the other problems on the list.
> 
> For more details Read [CONTRIBUTING.md](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md)

For your information [PR 2810](https://github.com/neetcode-gh/leetcode/pull/2797),  [PR 2710](https://github.com/neetcode-gh/leetcode/pull/2798) and many more PR was merged which does not mentioned in the Readme file. 
So Please use Strict rule on the from the first PR so i will not add more PR like that.

**Comment by sujal-goswami** [comment]
> > hey @chetannada, Problem `2520` is not mentioned in the Readme file. hence we are unable to merge it; nevertheless, you may help with the other problems on the list.
> > For more details Read [CONTRIBUTING.md](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md)
> 
> For your information [PR 2810](https://github.com/neetcode-gh/leetcode/pull/2797), [PR 2710](https://github.com/neetcode-gh/leetcode/pull/2798) and many more PR was merged which does not mentioned in the Readme file. So Please use Strict rule on the from the first PR so i will not add more PR like that.

hhf

**Comment by sujal-goswami** [comment]
image

We were instructed to follow what is expressly stated in the Readme document.

**Comment by chetannada** [comment]
> image
> We were instructed to follow what is expressly stated in the Readme document.

> Q: What if the problem I want to add isn't in the Neetcode 150 list or Missing Solutions table?

> A: Questions outside of the Neetcode 150 list can be added but please prioritise adding the listed solutions first.`

In Answer: It already written the it can be added `not written like that can not be added` or `Your PR will not merge if you post the different solution here`, I think you need to Update [CONTRIBUTING.md](https://github.com/neetcode-gh/leetcode/blob/main/CONTRIBUTING.md) for this.

Hi, @felivalencia3 Can you throw some light on this? Thanks.

**Pull request closed without merging**
