### PR TITLE
0560-subarray-sum-equals-k.py added and Updated README

### PR DESCRIPTION
**Pull request by AakashPawanGPS**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _0560-subarray-sum-equals-k.py._
- **Language(s) Used**: _python._
- **Submission URL**: _https://leetcode.com/problems/subarray-sum-equals-k/submissions/878792402/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### CODE REVIEW

**Comment by AakashPawanGPS** [comment]
Neetcode is doing great. I would be very happy to be a contributor to Neetcode. Review the PR. Hope My PR will get accepted.

**Review by AakashPawanGPS — COMMENTED** [review]
Added a Python solution for the problem 0560-subarray-sum-equals-k
Updated the README file

**Review by tahsintunan — CHANGES_REQUESTED** [review]
Hey, thanks for the PR. Our GitHub workflow periodically scans the repo and updates the README.md file automatically. So you don't need to manually update the README file. So just pushing the code would just be fine.

Everything else looks great!

**Comment by AakashPawanGPS** [comment]
Changed Done.

**Review by tahsintunan — APPROVED** [review]

**Pull request merged**
