### PR TITLE
Create 2038-remove-colored-pieces-if-both-neighbors-are-the-same-color

### PR DESCRIPTION
**Pull request by aadil42**
Solved 2038-remove-colored-pieces-if-both-neighbors-are-the-same-color in JS.

File(s) Added: 2038-remove-colored-pieces-if-both-neighbors-are-the-same-color.js
Language(s) Used: JavaScript
Submission URL: https://leetcode.com/problems/remove-colored-pieces-if-both-neighbors-are-the-same-color/submissions/1314237826/

### CODE REVIEW

**Comment by Ykhan799** [comment]
@aadil42 Solution looks good, add spacing for all control flow statements

**Comment by aadil42** [comment]
@Ykhan799, I have added spaces after control flow statements in all the PRs. Please review.

**Comment by Ykhan799** [comment]
@aadil42 Thanks for your contributions. I merged all the PRs I reviewed. I know you have several others remaining open. I'll review those in the next few days 👍

**Comment by aadil42** [comment]
Sure bro. Yeah, those reviews have been going on for a while with @aakhtar3. He must be busy.

**Comment by aadil42** [comment]
@Ykhan799,  before you review, can you give me a heads up here so I can go fix the spacing issue so we don't have to go around that again. From now on, I will try to add spacing after control flow when writing code. But a heads up before you begin review would save us time.

**Pull request merged**
