### PR TITLE
Create 1721-swapping-nodes-in-a-Linked-List.java

### PR DESCRIPTION
**Pull request by viet2307**
- **File(s) Modified**: java/1721-swapping-nodes-in-a-Linked-List.java
- **Language(s) Used**: Java
- **Submission URL**:  https://leetcode.com/problems/swapping-nodes-in-a-linked-list/submissions/1073319925/

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Review by sujal-goswami — CHANGES_REQUESTED** [review]
There is no need to write Auther, Name, etc only Time and space Complexity is fine.

**Comment by viet2307** [comment]
Sorry, force of habit.

**Review by sujal-goswami — APPROVED** [review]

**Review by sujal-goswami — CHANGES_REQUESTED** [review]
Please check the already written solution If your solution uses a different approach then you can just add your solution just below separately from the previous one.

**Comment by viet2307** [comment]
When I submit a PR there are no solution for this question yet, so it seems it was merged before mine.
Anyway, I'll close this PR then, cheers.

**Pull request closed without merging**
