### PR TITLE
Create 0147-insertion-sort-list.go

### PR DESCRIPTION
**Pull request by ashishsingh1508**
Added result of insertion sort for linked list

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _0001-two-sum.py, 0002-add-two-numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by a93a** [comment]
Hi, could you please provide your leetcode submission URL, and also add correct file extention to your file name. Thanks!

**Comment by ashishsingh1508** [comment]
You can ignore/reject it, I don't care. I am just trying to help add golang code, because the previously added one are really poorly written like https://github.com/neetcode-gh/leetcode/blob/main/go/0912-sort-an-array.go

Not here to prove something by submitting link to leetcode etc

**Comment by ashishsingh1508** [comment]
and the above one is added in example of insertion sort, bubble sort and merge sort lessons. I am just trying to add correct code. I don't submit code on leetcode I write it locally

**Review by ashishsingh1508 — COMMENTED** [review]
Changed extension

**Comment by Ykhan799** [comment]
@ashishsingh1508 Thanks for your contribution 👍

**Pull request merged**
