### PR TITLE
Create 0068-text-justification.java

### PR DESCRIPTION
**Pull request by dmgodoy**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _0068-text-justification.java_
- **Language(s) Used**: _java_
- **Submission URL**: _https://leetcode.com/problems/text-justification/submissions/1442197375/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by Ykhan799** [comment]
@dmgodoy There's already 2 other PRs for this solution #3354 and #3329. I'll take a look and see which one to merge

**Comment by dmgodoy** [comment]
Remove wrongly added java/0280-wiggle-sort.java (sent in a different pr) and fixed spacing in java/0068-text-justification.java

**Comment by Ykhan799** [comment]
@dmgodoy Thank you for your contributions 👍

**Comment by dmgodoy** [comment]
Great, thanks @Ykhan799 !

**Pull request merged**
