### PR TITLE
Create 0221-maximal-square.java Bottom Up tabulation

### PR DESCRIPTION
**Pull request by user54778**
[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: 0001-two-sum.py, 0002-add-two-numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

### CODE REVIEW

**Comment by a93a** [comment]
Hi @user54778, Thanks for the contribution, looks good. Could you please also provide the Leetcode submission url  as mentioned in the PR template? It makes it easier to check your solution and faster to get it merged. Also, please could you make sure to fill in the whole PR template next time, it would be appreciated!

Thanks in advance.

**Comment by user54778** [comment]
@a93a https://leetcode.com/problems/maximal-square/ 
Also, yes, I'll make sure to fill in the template next time! Thanks!

**Comment by tahsintunan** [comment]
Hey @user54778 , you've provided the link to the problem itself. But what we need is the submission URL of the solution you've submitted (looks sth like this: https://leetcode.com/problems/lexicographically-smallest-equivalent-string/submissions/880231371/). You can find the submission link by clicking on the **Submissions** tab and then selecting the solution you've submitted.

**Comment by user54778** [comment]
Ah sorry, misunderstood the question. Here is the submission link: https://leetcode.com/problems/maximal-square/submissions/877011521/ @tahsintunan

**Review by tahsintunan — APPROVED** [review]

**Pull request merged**
